version: "3.8"
services:
  # chanchito:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   links:
  #     - monguito
  postgres-db:
    image: postgres:16
    ports: 
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=bugsmanager